### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by mohomedanees** [zellwk/source-for-automating-workflow-book#3]
Hi Zell. When I ran gulp after downloading your code it gave an error as below. Can you please help me how to fix this issue?
![screen shot 2018-05-14 at 4 37 43 pm](https://user-images.githubusercontent.com/12741808/39993968-67a632e8-5795-11e8-8537-3a56eb60c626.png)

**Comment by zellwk** [comment]
Try creating a secrets.json file. I might have hard coded this in. Sorry!

Stay awesome,
Zell

On 14 May 2018 at 7:09:52 PM, mohomedanees (notifications@github.com) wrote:

Hi Zell. When I ran gulp after downloading your code it gave an error as
below. Can you please help me how to fix this issue?
[image: screen shot 2018-05-14 at 4 37 43 pm]
<https://user-images.githubusercontent.com/12741808/39993968-67a632e8-5795-11e8-8537-3a56eb60c626.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zellwk/source-for-automating-workflow-book/issues/3>,
or mute the thread

**Comment by mohomedanees** [comment]
Is that just an empty file ? and in which folder I have to create this file ?

**Comment by zellwk** [comment]
@mohomedanees Try making an empty file for now. From the error, it looks like the root folder.

**Comment by mohomedanees** [comment]
Thank you Zell.
